### ISSUE TITLE
Windows Universal

### ISSUE THREAD

**Issue by 130nk3r5** [conceptdev/xamarin-evolve-2014#1]
Good day,

I've added a Universal Windows application and tried to use this with no success. My Android,iOS and WP works 100% but I cannot get the Universal app to work with this. Is it possible?
Just to clarify, I used the solution to extract the LanguageResource.resx to a PCL and now I can use this for the 3 different platforms, but not for the Universal app.

In the class L10n.cs the GetString function always returns a null value...

Regards,
Hugo

**Comment by tobiasstraub** [comment]
@130nk3r5 Please provide more information. Which example do you use? Please show us your code if you want detailed help. If it is a general question please post this on [Stackoverflow](http://stackoverflow.com/questions/tagged/xamarin) or in [Xamarin Forums](https://forums.xamarin.com/). Thanks.

**Comment by 130nk3r5** [comment]
Don't worry... I made my own implementation for the Universal Windows platform. Seems to work 100% now.
